import random

TRINKETS = ['A mummifed golbin hand', 'A piece of crystal that faintly glows in the  moonligth',
            'A gold coin minted in an unknown land', 'A dairy written in a language you dont know',
            'A brass ring that never tarnishes', 'An old chess piece made from glass',
            'A pair of knucklebones dice, each with a skull symbol on the side that would show the six',
            'A small idol depicting a nightmarish creature that gives youunsettling dreams when you sleep near it',
            'A rope necklace from which dangles four mummified elf fingers',
            'A deed for a parcel of land in a realm unknown to you', 'A bright green finger', 'A small cloth doll skewered with needles',
            'A tooth from an unknown beast', 'An enormous scale, perhaps from a dragon', 'A bright green feather'
            'An old divination card bearing your likeness', 'A 1 ounce block made from an unknown material',
            'A glass orb filled with moving smoke', 'A 1 pound egg with a bright red shell', 'A pipe that blows bubble',
            'A glass jar containging a weird bit of flesh floating in pickling fluid', 'A multi-colored stone disk',
            'A ting gnome-crafted music box that plays a song you dimly remember from your childhood', 'A tiny silver icon of a raven',
            'A small wooden statuette of a smug halfing', 'A pair of old socks', 'A kinife that belonged to a relative',
            'A bag containing forty-seven humanoid teeth, one of which is rotten', 
            'A shard of obsidian that always feels warm to the touch', 'A glass vial filled with nail clippings',
            'A blank book whose page refuse to hold ink, chalk, graphite or any substance or marking',
            'A silver badge in the shape of a five point star', 'A vest with one hundred tiny pockets',
            'A rectangle metal device with two timy metal cups on one end that throws sparks when wet',
            'A small weightless stone block', 'A tiny sketch portrait of a goblin',
            'An empty glass vial that smells of perfume when opened', 'A scrap of cloth from an old banner',
            'A gemstone that looks like a lump of coal when examined by anoyone but you', 'A rank insignia from a lost legionaire',
            'A white, sequined glove sized for a human',
            'A vest with one hundred tiny pockets',
            'A small, weightless stone block',
            'A tiny sketch portrait of a goblin',
            'An empty glass vial that smells of perfume when opened',
            'A gemstone that looks like a lump of coal when examined by anyone but you',
            'A scrap of cloth from an old banner',
            'A rank insignia from a lost legionnaire',
            'A tiny silver bell without a clapper',
            'A mechanical canary inside a gnomish lamp',
            'A tiny chest carved to look like it has numerous feet on the bottom',
            'A dead sprite inside a clear glass bottle',
            'A metal can that has no opening but sounds as if it is filled with liquid, sand, spiders, or broken glass (your choice)',
            'A glass orb filled with water, in which swims a clockwork goldfish',
            "A silver spoon with an 'M' engraved on the handle",
            'A whistle made from gold-colored wood',
            'A dead scarab beetle the size of your hand',
            'Two toy soldiers, one with a missing head',
            'A small box filled with different-sized buttons',
            "A candle that can't be lit",
            'A tiny cage with no door',
            'An old key',
            'An indecipherable treasure map',
            'A hilt from a broken sword',
            "A rabbit's foot",
            'A glass eye',
            'A cameo carved in the likeness of a hideous person',
            'A silver skull the size of a coin',
            'An alabaster mask',
            'A pyramid of sticky black incense that smells very bad',
            'A nightcap that, when worn, gives you pleasant dreams',
            'A single caltrop made from bone',
            'A gold monocle frame without the lens',
            'A 1-inch cube, each side painted a different color',
            'A crystal knob from a door',
            'A small packet filled with pink dust',
            'A fragment of a beautiful song, written as musical notes on two pieces of parchment',
            'A silver teardrop earring made from a real teardrop',
            'The shell of an egg painted with scenes of human misery in disturbing detail',
            'A fan that, when unfolded, shows a sleeping cat',
            'A set of bone pipes',
            'A four-leaf clover pressed inside a book discussing manners and etiquette',
            'A sheet of parchment upon which is drawn a complex mechanical contraption',
            'An ornate scabbard that fits no blade you have found so far',
            'An invitation to a party where a murder happened',
            "A bronze pentacle with an etching of a rat's head in its center",
            'A purple handkerchief embroidered with the name of a powerful archmage',
            'Half of a floorplan for a temple, castle, or some other structure',
            'A bit of folded cloth that, when unfolded, turns into a stylish cap',
            'A receipt of deposit at a bank in a far-flung city',
            'A diary with seven missing pages',
            'An empty silver snuffbox bearing an inscription on the surface that says "dreams"',
            'An iron holy symbol devoted to an unknown god',
            "A book that tells the story of a legendary hero's rise and fall, with the last chapter missing",
            'A vial of dragon blood',
            'An ancient arrow of elven design',
            'A needle that never bends',
            'An ornate brooch of dwarven design',
            'An empty wine bottle bearing a pretty label that says, "The Wizard of Wines Winery, Red Dragon Crush, 331422-W"',
            'A mosaic tile with a multicolored, glazed surface',
            'A petrified mouse',
            "A black pirate flag adorned with a dragon's skull and crossbones",
            "A tiny mechanical crab or spider that moves about when it's not being observed",
            'A glass jar containing lard with a label that reads, "Griffon Grease"',
            'A wooden box with a ceramic bottom that holds a living worm with a head on each end of its body',
            'A metal urn containing the ashes of a hero'



            ]

item = random.choice(TRINKETS)
print(item)